[colors.primary]
background = '#18111a'
foreground = '#ecdeec'

[colors.cursor]
text = '#18111a'
cursor = '#ecdeec'

[colors.vi_mode_cursor]
text = '#18111a'
cursor = '#afc6ff'

[colors.search.matches]
foreground = '#504255'
background = '#e2b7f4'

[colors.search.focused_match]
foreground = '#504255'
background = '#afc6ff'

[colors.footer_bar]
foreground = '#504255'
background = '#ecdeec'

[colors.hints.start]
foreground = '#504255'
background = '#afc6ff'

[colors.hints.end]
foreground = '#504255'
background = '#afc6ff'

[colors.selection]
text = '#d3c0d8'
background = '#504255'


[colors.normal]
black   = '#504255'
red     = '#ffb4ab'
green   = '#afc6ff'
yellow  = '#afc6ff'
blue    = '#e2b7f4'
magenta = '#afc6ff'
cyan    = '#afc6ff'
white   = '#ecdeec'


[colors.bright]
black   = '#9c8ba1'
red     = '#ffb4ab'
green   = '#afc6ff'
yellow  = '#afc6ff'
blue    = '#e2b7f4'
magenta = '#afc6ff'
cyan    = '#afc6ff'
white   = '#ecdeec'


[colors.dim]
black   = '#504255'
red     = '#ffb4ab'
green   = '#afc6ff'
yellow  = '#afc6ff'
blue    = '#e2b7f4'
magenta = '#afc6ff'
cyan    = '#afc6ff'
white   = '#ecdeec'
