color0 #324b4c
color1 #ffb4ab
color2 #8ad88f
color3 #9ed49d
color4 #80d4d6
color5 #8ad88f
color6 #9ed49d
color7 #d7e5e5
color8 #7b9696
color9 #ffb4ab
color10 #8ad88f
color11 #9ed49d
color12 #80d4d6
color13 #8ad88f
color14 #9ed49d
color15 #d7e5e5

cursor                #d7e5e5
cursor_text_color     #091516
background            #091516
foreground            #d7e5e5
selection_foreground  #b0cccc
selection_background  #324b4c
active_border_color   #8ad88f
inactive_border_color #324b4c
url_color             #8ad88f

active_tab_foreground   #003911
active_tab_background   #8ad88f
inactive_tab_foreground #b0cccc
inactive_tab_background #324b4c
cursor_trail_color      #b0cccc
