color0 #504255
color1 #ffb4ab
color2 #afc6ff
color3 #afc6ff
color4 #e2b7f4
color5 #afc6ff
color6 #afc6ff
color7 #ecdeec
color8 #9c8ba1
color9 #ffb4ab
color10 #afc6ff
color11 #afc6ff
color12 #e2b7f4
color13 #afc6ff
color14 #afc6ff
color15 #ecdeec

cursor                #ecdeec
cursor_text_color     #18111a
background            #18111a
foreground            #ecdeec
selection_foreground  #d3c0d8
selection_background  #504255
active_border_color   #afc6ff
inactive_border_color #504255
url_color             #afc6ff

active_tab_foreground   #002d6c
active_tab_background   #afc6ff
inactive_tab_foreground #d3c0d8
inactive_tab_background #504255
cursor_trail_color      #d3c0d8
